### PR TITLE
Fixing stopService method for Android

### PR DESCRIPTION
**Pull request by widavies**
Addressing #126 for Android.

Still needs fixing on iOS as well, might take a look at this when I have a moment.

### CODE REVIEW

**Comment by ekasetiawans** [comment]
thanks

**Comment by ekasetiawans** [comment]
@widavies we have to stop the AlarmManager too, because the AlarmManager used to start service automatically if the service killed.

**Comment by ekasetiawans** [comment]
Here is the implementation of stopService method
https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service_android/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java at line 280

So, that means, we have to call `stopService` from the service isolate not from the main isolate (UI). But we can also `sendData`  from the main isolate (UI) to service isolate.

**Comment by widavies** [comment]
Oh yeah you're right, let me know if you need any more help on this, I might take a stab at the iOS implementation for it as well when I have some time.

**Comment by widavies** [comment]
@ekasetiawans After further inspection, it kind of seems like this just isn't a problem when I run from master? Maybe the latest version of the package hasn't been pushed to pub?

**Comment by widavies** [comment]
Okay so this just turns out to be a dumb error on my part, I was calling:
```dart
FlutterBackgroundService().stopService();
```
instead of
```dart
FlutterBackgroundService().sendData({
  "action": "stopService"
});
```
So it seems like `FlutterBackgroundService().stopService()` should be either removed or updated to proxy to the `stopService` action within the service itself.

**Comment by ekasetiawans** [comment]
@widavies we still have to call `FlutterBackgroundService().stopService()` to stop the service, but we have to call it inside `onStart` method which is executed in background service isolate. 

See the example here
https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/lib/main.dart
at line 65 and 159

**Comment by Saikiran24** [comment]
Service not Work when app killed  in Android, Please fix this issue

**Pull request merged**
